### ISSUE TITLE
Creating tests for the bot

### ISSUE THREAD

**Issue by ayushtamra** [badging/badging-bot#11] opened 2022-05-01 12:40 UTC
### Description:

The tests in the Github app is useful for the developers to test the features of the app locally without repeatedly creating events on Github to check if code is working or not.

### Potential solution:

The tests can be implemented using jest or nock. Probot defines the usage of tests in their documentation which can be found out [here](https://probot.github.io/docs/testing/)

**Comment by kaxada** [comment] 2023-09-29 14:39
duplicate of https://github.com/badging/badging-bot/issues/1

**Closed by kaxada** 2023-09-29 14:39 UTC
Labels: enhancement
